name: Auto PR from staging to main

on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create or update pull request to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: staging
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Auto-merge: staging → main"
          pr_body: |
            This pull request was automatically created by a GitHub Action
            when code was pushed to the **staging** branch.
          pr_draft: false
